const validColumns =
  // the order of these columns is the order they will appear in the table
  // right now, we assume that if no bestScore is set, the rank column should not be populated with place numbers
  // TODO: we may want an explicit "showRank" property to determine if the rank column should be shown. 
  [
    {
      key: "_Index",
      name: "#",
      displayName: "#",
      align: "left",
      defaultSort: null,
      bestScore: null,
    },
    {
      key: "Name",
      name: "Name",
      displayName: "Name",
      align: "left",
      defaultSort: "asc",
      bestScore: null,
    },
    {
      key: "Buyins",
      name: "Buy-ins",
      displayName: "Games",
      align: "center",
      defaultSort: "desc",
      bestScore: null,
    },
    {
      key: "RebuysCount",
      name: "Rebuys",
      align: "center",
      defaultSort: "desc",
      bestScore: null,
    },
    {
      key: "TotalWinnings",
      name: "Total Winnings",
      displayName: "Won",
      align: "right",
      defaultSort: "desc",
      bestScore: "high",
      sortOnPageLoad: true,
      transform: transformMoney,
    },
    {
      key: "TotalCost",
      name: "Total Cost",
      displayName: "Cost",
      align: "right",
      defaultSort: "desc",
      bestScore: null,
      transform: transformMoney,
    },
    {
      key: "TotalTake",
      name: "Total Take",
      displayName: "Take",
      align: "right",
      defaultSort: "desc",
      bestScore: "high",
      transform: transformMoney,
    },
    {
      key: "TimesPlaced",
      name: "Times Placed",
      displayName: "Payouts",
      align: "center",
      defaultSort: "desc",
      bestScore: "high",
    },
    {
      key: "AveragePlaced",
      name: "Average Placed",
      displayName: "Payout %",
      align: "center",
      defaultSort: "desc",
      bestScore: "high",
      transform: transformAvgPlaced,
    },
    {
      key: "First",
      name: "1st",
      align: "center",
      defaultSort: "desc",
      bestScore: "high",
    },
    {
      key: "Second",
      name: "2nd",
      align: "center",
      defaultSort: "desc",
      bestScore: "high",
    },
    {
      key: "Third",
      name: "3rd",
      align: "center",
      defaultSort: "desc",
      bestScore: "high",
    },
    {
      key: "OnTheBubble",
      name: "Bubble",
      align: "center",
      defaultSort: "desc",
      bestScore: "high",
    },
    {
      key: "Hits",
      name: "Hits",
      align: "center",
      defaultSort: "desc",
      bestScore: "high",
      transform: transformHits,
    },
    {
      key: "AverageHits",
      name: "Average Hits",
      displayName: "Avg Hits",
      align: "center",
      defaultSort: "desc",
      bestScore: "high",
      transform: transformAvgHits,
    },
  ].map((col, index) => ({ ...col, order: index }));
